// The cursor artwork, in one place.
//
// Shared by `gen-cursors.cjs` (which writes the files) and `test-cursors.cjs`
// (which checks the files still match). Split out because a cursor's geometry and
// the hotspot written in the stylesheet have to agree, and two copies of the
// hotspot table is two chances to disagree.
//
// Cursors are the one piece of artwork on the site that cannot inherit a CSS
// custom property: `cursor: url(...)` loads the file as an image, in its own
// document, with no access to the page's variables. So the brand colour is baked
// into the files -- which means a value baked by hand goes stale the moment the
// theme changes, silently. Hence: read from CSS, generate, and let the test fail
// if anyone edits the output instead of re-running the generator.

const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..')
const css = fs.readFileSync(path.join(root, 'src', 'index.css'), 'utf8')

const brand = /--cc-brand:\s*(#[0-9a-fA-F]{3,8})\s*;/.exec(css)
if (!brand) {
  console.error('could not find --cc-brand in src/index.css')
  process.exit(1)
}
const INK = brand[1]

/**
 * The shapes, lifted from lucide's icon data so the cursors and the icon set are
 * the same drawing rather than two hand-rolled near-misses.
 *
 * `hotspot` is the point that must land under the real pointer, in the SVG's own
 * 24x24 units. The stylesheet repeats it in the `cursor: url() x y` pair, and the
 * test compares the two.
 */
const CURSORS = {
  // Open hand: over a zone you can drag. Lucide `hand`.
  grab: {
    lucide: 'hand',
    hotspot: [12, 13],
    paths: [
      { d: 'M18 11V6a2 2 0 0 0-2-2a2 2 0 0 0-2 2' },
      { d: 'M14 10V4a2 2 0 0 0-2-2a2 2 0 0 0-2 2v2' },
      { d: 'M10 10.5V6a2 2 0 0 0-2-2a2 2 0 0 0-2 2v8' },
      {
        d: 'M18 8a2 2 0 1 1 4 0v6a8 8 0 0 1-8 8h-2c-2.8 0-4.5-.86-5.99-2.34l-3.6-3.6a2 2 0 0 1 2.83-2.82L7 15',
      },
    ],
  },

  // Closed hand: while a drag is in progress. Lucide `hand-fist`.
  //
  // Closed because the thing is held. An open hand during a drag reads as "you
  // could pick this up again", which is the opposite of what is happening.
  grabbing: {
    lucide: 'hand-fist',
    hotspot: [12, 13],
    paths: [
      {
        d: 'M12.035 17.012a3 3 0 0 0-3-3l-.311-.002a.72.72 0 0 1-.505-1.229l1.195-1.195A2 2 0 0 1 10.828 11H12a2 2 0 0 0 0-4H9.243a3 3 0 0 0-2.122.879l-2.707 2.707A4.83 4.83 0 0 0 3 14a8 8 0 0 0 8 8h2a8 8 0 0 0 8-8V7a2 2 0 1 0-4 0v2a2 2 0 1 0 4 0',
      },
      { d: 'M13.888 9.662A2 2 0 0 0 17 8V5A2 2 0 1 0 13 5' },
      { d: 'M9 5A2 2 0 1 0 5 5V10' },
      { d: 'M9 7V4A2 2 0 1 1 13 4V7.268' },
    ],
  },

  // Open hand at the fingertip: over something a click opens. Lucide `hand`.
  //
  // The hotspot is the tip of the index finger -- the part that presses. Anywhere
  // else and the click lands somewhere other than where the finger is drawn, which
  // feels wrong in a way nobody can name.
  point: {
    lucide: 'hand',
    hotspot: [8, 4],
    paths: [
      { d: 'M18 11V6a2 2 0 0 0-2-2a2 2 0 0 0-2 2' },
      { d: 'M14 10V4a2 2 0 0 0-2-2a2 2 0 0 0-2 2v2' },
      { d: 'M10 10.5V6a2 2 0 0 0-2-2a2 2 0 0 0-2 2v8' },
      {
        d: 'M18 8a2 2 0 1 1 4 0v6a8 8 0 0 1-8 8h-2c-2.8 0-4.5-.86-5.99-2.34l-3.6-3.6a2 2 0 0 1 2.83-2.82L7 15',
      },
    ],
  },

  // The I-beam: over text you can select or type into. Lucide `type`.
  //
  // Hotspot is dead centre, which for a symmetric I-beam is exactly right.
  text: {
    lucide: 'type',
    hotspot: [12, 12],
    paths: [{ d: 'M12 4v16' }, { d: 'M4 7V5a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v2' }, { d: 'M9 20h6' }],
  },
}

/** Render one cursor's SVG, with the comment header that explains it in place. */
function render(name, spec) {
  const paths = spec.paths
    .map((p) => `    <path d="${p.d}" />`)
    .join('\n')
  const [hx, hy] = spec.hotspot

  return `<!--
  GENERATED by scripts/gen-cursors.cjs -- do not edit by hand.

  The ${name} cursor, in the theme's primary colour (${INK}, read from
  --cc-brand in src/index.css).

  Hotspot: ${hx},${hy} in this file's own 24x24 units. The stylesheet repeats it
  in the cursor: url(...) ${hx} ${hy} pair; test-cursors.cjs fails if the two
  disagree.

  Two passes, because a cursor cannot inherit a page colour: a 4.5px white stroke
  underneath, then a 2px ${INK} stroke on top. The white reads against a dark card
  and the brand colour against a white one. Drawn at 24 rather than snapshotted to
  32 or 64, so it stays sharp on a HiDPI display instead of going soft.

  Shape: lucide's "${spec.lucide}", so the cursors and the icon set are one
  drawing rather than two near-misses.
-->
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke-linecap="round" stroke-linejoin="round">
  <g stroke="#ffffff" stroke-width="4.5">
${paths}
  </g>
  <g stroke="${INK}" stroke-width="2">
${paths}
  </g>
</svg>
`
}

module.exports = { INK, CURSORS, render, root }
